# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWndPwUbvI.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDateTimeEdit,
    QDockWidget, QDoubleSpinBox, QFrame, QGridLayout,
    QGroupBox, QHBoxLayout, QLabel, QLayout,
    QLineEdit, QListWidget, QListWidgetItem, QMainWindow,
    QMenu, QMenuBar, QPushButton, QRadioButton,
    QSizePolicy, QSpacerItem, QSpinBox, QStatusBar,
    QToolBar, QVBoxLayout, QWidget)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        if not mainWindow.objectName():
            mainWindow.setObjectName(u"mainWindow")
        mainWindow.setWindowModality(Qt.WindowModality.NonModal)
        mainWindow.setEnabled(True)
        mainWindow.resize(1000, 875)
        mainWindow.setMinimumSize(QSize(0, 0))
        mainWindow.setMaximumSize(QSize(16777215, 16777215))
        mainWindow.setSizeIncrement(QSize(0, 0))
        self.actionExit = QAction(mainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon = QIcon()
        icon.addFile(u"images/application-exit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExit.setIcon(icon)
        self.actionOpen = QAction(mainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon1 = QIcon()
        icon1.addFile(u"images/document-open.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpen.setIcon(icon1)
        self.actionHelp = QAction(mainWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        icon2 = QIcon()
        icon2.addFile(u"images/help-contents.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionHelp.setIcon(icon2)
        self.actionAbout = QAction(mainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon3 = QIcon()
        icon3.addFile(u"images/help-about.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionAbout.setIcon(icon3)
        self.actionSave = QAction(mainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon4 = QIcon()
        icon4.addFile(u"images/document-save-as.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave.setIcon(icon4)
        self.actionNext = QAction(mainWindow)
        self.actionNext.setObjectName(u"actionNext")
        icon5 = QIcon()
        icon5.addFile(u"images/go-next.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNext.setIcon(icon5)
        self.actionPrevious = QAction(mainWindow)
        self.actionPrevious.setObjectName(u"actionPrevious")
        icon6 = QIcon()
        icon6.addFile(u"images/go-next-rtl.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPrevious.setIcon(icon6)
        self.actionReload = QAction(mainWindow)
        self.actionReload.setObjectName(u"actionReload")
        icon7 = QIcon()
        icon7.addFile(u"images/view-refresh.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionReload.setIcon(icon7)
        self.actionFirst = QAction(mainWindow)
        self.actionFirst.setObjectName(u"actionFirst")
        icon8 = QIcon()
        icon8.addFile(u"images/go-first.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionFirst.setIcon(icon8)
        self.actionLast = QAction(mainWindow)
        self.actionLast.setObjectName(u"actionLast")
        icon9 = QIcon()
        icon9.addFile(u"images/go-last.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLast.setIcon(icon9)
        self.actionChangeLayer = QAction(mainWindow)
        self.actionChangeLayer.setObjectName(u"actionChangeLayer")
        self.actionClose = QAction(mainWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionRemote = QAction(mainWindow)
        self.actionRemote.setObjectName(u"actionRemote")
        icon10 = QIcon()
        icon10.addFile(u"images/folder-remote.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRemote.setIcon(icon10)
        self.actionClean = QAction(mainWindow)
        self.actionClean.setObjectName(u"actionClean")
        icon11 = QIcon()
        icon11.addFile(u"images/Gartoon-Team-Gartoon-Action-Edit-clear-broom.24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionClean.setIcon(icon11)
        self.actionMoveLeft = QAction(mainWindow)
        self.actionMoveLeft.setObjectName(u"actionMoveLeft")
        icon12 = QIcon()
        icon12.addFile(u"images/icons8-open-pane-24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionMoveLeft.setIcon(icon12)
        self.actionMoveRight = QAction(mainWindow)
        self.actionMoveRight.setObjectName(u"actionMoveRight")
        icon13 = QIcon()
        icon13.addFile(u"images/icons8-close-pane-24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionMoveRight.setIcon(icon13)
        self.actionO_trace = QAction(mainWindow)
        self.actionO_trace.setObjectName(u"actionO_trace")
        self.actionO_trace.setCheckable(True)
        self.actionO_trace.setChecked(True)
        self.actionO_trace.setEnabled(False)
        icon14 = QIcon()
        icon14.addFile(u"images/o-trace.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon14.addFile(u"images/o-trace.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionO_trace.setIcon(icon14)
        self.actionX_trace = QAction(mainWindow)
        self.actionX_trace.setObjectName(u"actionX_trace")
        self.actionX_trace.setCheckable(True)
        self.actionX_trace.setChecked(True)
        self.actionX_trace.setEnabled(False)
        icon15 = QIcon()
        icon15.addFile(u"images/x-trace.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionX_trace.setIcon(icon15)
        self.actionIgnore_errors = QAction(mainWindow)
        self.actionIgnore_errors.setObjectName(u"actionIgnore_errors")
        self.actionIgnore_errors.setCheckable(True)
        icon16 = QIcon()
        icon16.addFile(u"images/Martz90-Circle-Addon2-Warning.24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionIgnore_errors.setIcon(icon16)
        self.action_ANN = QAction(mainWindow)
        self.action_ANN.setObjectName(u"action_ANN")
        icon17 = QIcon()
        icon17.addFile(u"images/neural-network.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_ANN.setIcon(icon17)
        self.centralwidget = QWidget(mainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)

        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(mainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1000, 33))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(mainWindow)
        self.statusbar.setObjectName(u"statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QDockWidget(mainWindow)
        self.dockWidget.setObjectName(u"dockWidget")
        self.dockWidget.setMinimumSize(QSize(180, 600))
        self.dockWidget.setMaximumSize(QSize(180, 600))
        self.dockWidget.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(Qt.DockWidgetArea.LeftDockWidgetArea)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.gridLayout_7 = QGridLayout(self.dockWidgetContents)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_6 = QGridLayout()
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.radioButtonF1 = QRadioButton(self.dockWidgetContents)
        self.radioButtonF1.setObjectName(u"radioButtonF1")
#if QT_CONFIG(tooltip)
        self.radioButtonF1.setToolTip(u"The F1 trace data group")
#endif // QT_CONFIG(tooltip)
        self.radioButtonF1.setText(u"F1")

        self.gridLayout_6.addWidget(self.radioButtonF1, 3, 0, 1, 2)

        self.doubleSpinBoxF2 = QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBoxF2.setObjectName(u"doubleSpinBoxF2")
        self.doubleSpinBoxF2.setSingleStep(0.010000000000000)

        self.gridLayout_6.addWidget(self.doubleSpinBoxF2, 1, 0, 1, 1)

        self.listWidgetF1 = QListWidget(self.dockWidgetContents)
        self.listWidgetF1.setObjectName(u"listWidgetF1")
        self.listWidgetF1.setEnabled(False)
#if QT_CONFIG(tooltip)
        self.listWidgetF1.setToolTip(u"The trace points (f in MHz, h' in km)\n"
"(Left-click)")
#endif // QT_CONFIG(tooltip)
        self.listWidgetF1.setSortingEnabled(True)

        self.gridLayout_6.addWidget(self.listWidgetF1, 5, 0, 1, 2)

        self.radioButtonF2 = QRadioButton(self.dockWidgetContents)
        self.radioButtonF2.setObjectName(u"radioButtonF2")
#if QT_CONFIG(tooltip)
        self.radioButtonF2.setToolTip(u"The F2 trace data group")
#endif // QT_CONFIG(tooltip)
        self.radioButtonF2.setText(u"F2")
        self.radioButtonF2.setChecked(True)

        self.gridLayout_6.addWidget(self.radioButtonF2, 0, 0, 1, 2)

        self.radioButtonEs = QRadioButton(self.dockWidgetContents)
        self.radioButtonEs.setObjectName(u"radioButtonEs")

        self.gridLayout_6.addWidget(self.radioButtonEs, 9, 0, 1, 2)

        self.buttonClearF1 = QPushButton(self.dockWidgetContents)
        self.buttonClearF1.setObjectName(u"buttonClearF1")
        self.buttonClearF1.setEnabled(False)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonClearF1.sizePolicy().hasHeightForWidth())
        self.buttonClearF1.setSizePolicy(sizePolicy)
        self.buttonClearF1.setText(u"")
        icon18 = QIcon()
        icon18.addFile(u"images/icons8-close-16.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.buttonClearF1.setIcon(icon18)
        self.buttonClearF1.setIconSize(QSize(16, 16))

        self.gridLayout_6.addWidget(self.buttonClearF1, 4, 1, 1, 1)

        self.listWidgetE = QListWidget(self.dockWidgetContents)
        self.listWidgetE.setObjectName(u"listWidgetE")
        self.listWidgetE.setEnabled(False)
#if QT_CONFIG(tooltip)
        self.listWidgetE.setToolTip(u"The trace points (f in MHz, h' in km)\n"
"(Left-click)")
#endif // QT_CONFIG(tooltip)
        self.listWidgetE.setSortingEnabled(True)

        self.gridLayout_6.addWidget(self.listWidgetE, 8, 0, 1, 2)

        self.buttonClearE = QPushButton(self.dockWidgetContents)
        self.buttonClearE.setObjectName(u"buttonClearE")
        self.buttonClearE.setEnabled(False)
        self.buttonClearE.setIcon(icon18)
        self.buttonClearE.setIconSize(QSize(16, 16))

        self.gridLayout_6.addWidget(self.buttonClearE, 7, 1, 1, 1)

        self.buttonClearEs = QPushButton(self.dockWidgetContents)
        self.buttonClearEs.setObjectName(u"buttonClearEs")
        self.buttonClearEs.setEnabled(False)
        self.buttonClearEs.setIcon(icon18)

        self.gridLayout_6.addWidget(self.buttonClearEs, 10, 1, 1, 1)

        self.doubleSpinBoxF1 = QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBoxF1.setObjectName(u"doubleSpinBoxF1")
        self.doubleSpinBoxF1.setEnabled(False)
        self.doubleSpinBoxF1.setSingleStep(0.010000000000000)

        self.gridLayout_6.addWidget(self.doubleSpinBoxF1, 4, 0, 1, 1)

        self.buttonClearF2 = QPushButton(self.dockWidgetContents)
        self.buttonClearF2.setObjectName(u"buttonClearF2")
        self.buttonClearF2.setText(u"")
        self.buttonClearF2.setIcon(icon18)
        self.buttonClearF2.setIconSize(QSize(16, 16))
        self.buttonClearF2.setAutoDefault(False)
        self.buttonClearF2.setFlat(False)

        self.gridLayout_6.addWidget(self.buttonClearF2, 1, 1, 1, 1)

        self.radioButtonE = QRadioButton(self.dockWidgetContents)
        self.radioButtonE.setObjectName(u"radioButtonE")
#if QT_CONFIG(tooltip)
        self.radioButtonE.setToolTip(u"The E trace data group")
#endif // QT_CONFIG(tooltip)
        self.radioButtonE.setText(u"E")
        self.radioButtonE.setChecked(False)

        self.gridLayout_6.addWidget(self.radioButtonE, 6, 0, 1, 2)

        self.doubleSpinBoxE = QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBoxE.setObjectName(u"doubleSpinBoxE")
        self.doubleSpinBoxE.setEnabled(False)
        self.doubleSpinBoxE.setSingleStep(0.010000000000000)

        self.gridLayout_6.addWidget(self.doubleSpinBoxE, 7, 0, 1, 1)

        self.doubleSpinBoxEs = QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBoxEs.setObjectName(u"doubleSpinBoxEs")
        self.doubleSpinBoxEs.setEnabled(False)
        self.doubleSpinBoxEs.setSingleStep(0.010000000000000)

        self.gridLayout_6.addWidget(self.doubleSpinBoxEs, 10, 0, 1, 1)

        self.listWidgetF2 = QListWidget(self.dockWidgetContents)
        self.listWidgetF2.setObjectName(u"listWidgetF2")
        self.listWidgetF2.setEnabled(True)
#if QT_CONFIG(tooltip)
        self.listWidgetF2.setToolTip(u"The trace points (f in MHz, h' in km)\n"
"(Left-click)")
#endif // QT_CONFIG(tooltip)
        self.listWidgetF2.setSortingEnabled(True)

        self.gridLayout_6.addWidget(self.listWidgetF2, 2, 0, 1, 2)

        self.listWidgetEs = QListWidget(self.dockWidgetContents)
        self.listWidgetEs.setObjectName(u"listWidgetEs")
        self.listWidgetEs.setEnabled(False)
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.listWidgetEs.sizePolicy().hasHeightForWidth())
        self.listWidgetEs.setSizePolicy(sizePolicy1)

        self.gridLayout_6.addWidget(self.listWidgetEs, 11, 0, 1, 2)


        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)

        self.dockWidget.setWidget(self.dockWidgetContents)
        mainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockWidget)
        self.toolBar = QToolBar(mainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setEnabled(True)
        mainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.dockWidget_2 = QDockWidget(mainWindow)
        self.dockWidget_2.setObjectName(u"dockWidget_2")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.dockWidget_2.sizePolicy().hasHeightForWidth())
        self.dockWidget_2.setSizePolicy(sizePolicy2)
        self.dockWidget_2.setMinimumSize(QSize(297, 633))
        self.dockWidget_2.setMaximumSize(QSize(300, 8000))
        self.dockWidget_2.setFloating(False)
        self.dockWidget_2.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidget_2.setAllowedAreas(Qt.DockWidgetArea.RightDockWidgetArea)
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.gridLayout = QGridLayout(self.dockWidgetContents_2)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SizeConstraint.SetMinimumSize)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.groupBox_2 = QGroupBox(self.dockWidgetContents_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy3)
        self.groupBox_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.groupBox_2.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.verticalLayout_3 = QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4 = QGridLayout()
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setSizeConstraint(QLayout.SizeConstraint.SetMinimumSize)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.pngWidthSpinBox = QSpinBox(self.groupBox_2)
        self.pngWidthSpinBox.setObjectName(u"pngWidthSpinBox")
        self.pngWidthSpinBox.setMinimum(5)
        self.pngWidthSpinBox.setMaximum(10)
        self.pngWidthSpinBox.setValue(10)

        self.gridLayout_4.addWidget(self.pngWidthSpinBox, 4, 1, 1, 1)

        self.pngDefaultButton = QPushButton(self.groupBox_2)
        self.pngDefaultButton.setObjectName(u"pngDefaultButton")

        self.gridLayout_4.addWidget(self.pngDefaultButton, 7, 0, 1, 2)

        self.pngCheckBox = QCheckBox(self.groupBox_2)
        self.pngCheckBox.setObjectName(u"pngCheckBox")
        self.pngCheckBox.setChecked(True)

        self.gridLayout_4.addWidget(self.pngCheckBox, 3, 0, 1, 2)

        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")

        self.gridLayout_4.addWidget(self.label_7, 6, 0, 1, 1)

        self.pngDpiSpinBox = QSpinBox(self.groupBox_2)
        self.pngDpiSpinBox.setObjectName(u"pngDpiSpinBox")
        self.pngDpiSpinBox.setMinimum(100)
        self.pngDpiSpinBox.setMaximum(300)
        self.pngDpiSpinBox.setSingleStep(50)

        self.gridLayout_4.addWidget(self.pngDpiSpinBox, 6, 1, 1, 1)

        self.stdCheckBox = QCheckBox(self.groupBox_2)
        self.stdCheckBox.setObjectName(u"stdCheckBox")
        self.stdCheckBox.setChecked(True)

        self.gridLayout_4.addWidget(self.stdCheckBox, 1, 0, 1, 1)

        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")

        self.gridLayout_4.addWidget(self.label_6, 5, 0, 1, 1)

        self.pngHeightSpinBox = QSpinBox(self.groupBox_2)
        self.pngHeightSpinBox.setObjectName(u"pngHeightSpinBox")
        self.pngHeightSpinBox.setMinimum(5)
        self.pngHeightSpinBox.setMaximum(10)
        self.pngHeightSpinBox.setValue(6)

        self.gridLayout_4.addWidget(self.pngHeightSpinBox, 5, 1, 1, 1)

        self.line = QFrame(self.groupBox_2)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.gridLayout_4.addWidget(self.line, 2, 0, 1, 2)

        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setObjectName(u"label_5")

        self.gridLayout_4.addWidget(self.label_5, 4, 0, 1, 1)

        self.jsonCheckBox = QCheckBox(self.groupBox_2)
        self.jsonCheckBox.setObjectName(u"jsonCheckBox")
        self.jsonCheckBox.setChecked(True)

        self.gridLayout_4.addWidget(self.jsonCheckBox, 0, 0, 1, 1)


        self.verticalLayout_3.addLayout(self.gridLayout_4)


        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 1)

        self.groupBox = QGroupBox(self.dockWidgetContents_2)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy3)
        self.groupBox.setMinimumSize(QSize(0, 0))
        self.groupBox.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.verticalLayout = QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5 = QGridLayout()
        self.gridLayout_5.setSpacing(5)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")

        self.gridLayout_5.addWidget(self.label_4, 9, 0, 1, 1)

        self.sunspotNumberLabel = QLabel(self.groupBox)
        self.sunspotNumberLabel.setObjectName(u"sunspotNumberLabel")

        self.gridLayout_5.addWidget(self.sunspotNumberLabel, 6, 0, 1, 1)

        self.latLineEdit = QLineEdit(self.groupBox)
        self.latLineEdit.setObjectName(u"latLineEdit")
        self.latLineEdit.setEnabled(False)

        self.gridLayout_5.addWidget(self.latLineEdit, 2, 1, 1, 1)

        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")

        self.gridLayout_5.addWidget(self.label_8, 5, 0, 1, 1)

        self.dateTimeEdit = QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setObjectName(u"dateTimeEdit")
        self.dateTimeEdit.setEnabled(False)

        self.gridLayout_5.addWidget(self.dateTimeEdit, 8, 1, 1, 1)

        self.stationNameEdit = QLineEdit(self.groupBox)
        self.stationNameEdit.setObjectName(u"stationNameEdit")
        self.stationNameEdit.setEnabled(False)

        self.gridLayout_5.addWidget(self.stationNameEdit, 0, 1, 1, 1)

        self.longDegLabel = QLabel(self.groupBox)
        self.longDegLabel.setObjectName(u"longDegLabel")

        self.gridLayout_5.addWidget(self.longDegLabel, 3, 0, 1, 1)

        self.line_4 = QFrame(self.groupBox)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)

        self.gridLayout_5.addWidget(self.line_4, 1, 0, 1, 2)

        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")

        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)

        self.line_3 = QFrame(self.groupBox)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)

        self.gridLayout_5.addWidget(self.line_3, 7, 0, 1, 2)

        self.timeZoneComboBox = QComboBox(self.groupBox)
        self.timeZoneComboBox.setObjectName(u"timeZoneComboBox")
        self.timeZoneComboBox.setEnabled(False)

        self.gridLayout_5.addWidget(self.timeZoneComboBox, 9, 1, 1, 1)

        self.longLineEdit = QLineEdit(self.groupBox)
        self.longLineEdit.setObjectName(u"longLineEdit")
        self.longLineEdit.setEnabled(False)

        self.gridLayout_5.addWidget(self.longLineEdit, 3, 1, 1, 1)

        self.dipAngleLineEdit = QLineEdit(self.groupBox)
        self.dipAngleLineEdit.setObjectName(u"dipAngleLineEdit")
        self.dipAngleLineEdit.setEnabled(False)

        self.gridLayout_5.addWidget(self.dipAngleLineEdit, 5, 1, 1, 1)

        self.sunspotNumberLineEdit = QLineEdit(self.groupBox)
        self.sunspotNumberLineEdit.setObjectName(u"sunspotNumberLineEdit")
        self.sunspotNumberLineEdit.setEnabled(False)

        self.gridLayout_5.addWidget(self.sunspotNumberLineEdit, 6, 1, 1, 1)

        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")

        self.gridLayout_5.addWidget(self.label_3, 8, 0, 1, 1)

        self.gyrofrequencyLineEdit = QLineEdit(self.groupBox)
        self.gyrofrequencyLineEdit.setObjectName(u"gyrofrequencyLineEdit")
        self.gyrofrequencyLineEdit.setEnabled(False)

        self.gridLayout_5.addWidget(self.gyrofrequencyLineEdit, 4, 1, 1, 1)

        self.latDegLabel = QLabel(self.groupBox)
        self.latDegLabel.setObjectName(u"latDegLabel")

        self.gridLayout_5.addWidget(self.latDegLabel, 2, 0, 1, 1)

        self.gyrofrequencyLabel = QLabel(self.groupBox)
        self.gyrofrequencyLabel.setObjectName(u"gyrofrequencyLabel")

        self.gridLayout_5.addWidget(self.gyrofrequencyLabel, 4, 0, 1, 1)


        self.verticalLayout.addLayout(self.gridLayout_5)


        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.gridLayout.addItem(self.verticalSpacer, 3, 0, 1, 1)

        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        mainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.dockWidget_2)
        QWidget.setTabOrder(self.radioButtonF2, self.doubleSpinBoxF2)
        QWidget.setTabOrder(self.doubleSpinBoxF2, self.buttonClearF2)
        QWidget.setTabOrder(self.buttonClearF2, self.listWidgetF2)
        QWidget.setTabOrder(self.listWidgetF2, self.radioButtonF1)
        QWidget.setTabOrder(self.radioButtonF1, self.doubleSpinBoxF1)
        QWidget.setTabOrder(self.doubleSpinBoxF1, self.buttonClearF1)
        QWidget.setTabOrder(self.buttonClearF1, self.listWidgetF1)
        QWidget.setTabOrder(self.listWidgetF1, self.radioButtonE)
        QWidget.setTabOrder(self.radioButtonE, self.doubleSpinBoxE)
        QWidget.setTabOrder(self.doubleSpinBoxE, self.buttonClearE)
        QWidget.setTabOrder(self.buttonClearE, self.listWidgetE)
        QWidget.setTabOrder(self.listWidgetE, self.radioButtonEs)
        QWidget.setTabOrder(self.radioButtonEs, self.doubleSpinBoxEs)
        QWidget.setTabOrder(self.doubleSpinBoxEs, self.buttonClearEs)
        QWidget.setTabOrder(self.buttonClearEs, self.listWidgetEs)
        QWidget.setTabOrder(self.listWidgetEs, self.stationNameEdit)
        QWidget.setTabOrder(self.stationNameEdit, self.latLineEdit)
        QWidget.setTabOrder(self.latLineEdit, self.longLineEdit)
        QWidget.setTabOrder(self.longLineEdit, self.gyrofrequencyLineEdit)
        QWidget.setTabOrder(self.gyrofrequencyLineEdit, self.dipAngleLineEdit)
        QWidget.setTabOrder(self.dipAngleLineEdit, self.sunspotNumberLineEdit)
        QWidget.setTabOrder(self.sunspotNumberLineEdit, self.dateTimeEdit)
        QWidget.setTabOrder(self.dateTimeEdit, self.timeZoneComboBox)
        QWidget.setTabOrder(self.timeZoneComboBox, self.jsonCheckBox)
        QWidget.setTabOrder(self.jsonCheckBox, self.stdCheckBox)
        QWidget.setTabOrder(self.stdCheckBox, self.pngCheckBox)
        QWidget.setTabOrder(self.pngCheckBox, self.pngWidthSpinBox)
        QWidget.setTabOrder(self.pngWidthSpinBox, self.pngHeightSpinBox)
        QWidget.setTabOrder(self.pngHeightSpinBox, self.pngDpiSpinBox)
        QWidget.setTabOrder(self.pngDpiSpinBox, self.pngDefaultButton)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionClose)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menu.addAction(self.actionHelp)
        self.menu.addAction(self.actionAbout)
        self.menuView.addAction(self.actionChangeLayer)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionRemote)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFirst)
        self.toolBar.addAction(self.actionPrevious)
        self.toolBar.addAction(self.actionReload)
        self.toolBar.addAction(self.actionNext)
        self.toolBar.addAction(self.actionLast)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMoveLeft)
        self.toolBar.addAction(self.actionMoveRight)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionO_trace)
        self.toolBar.addAction(self.actionX_trace)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionIgnore_errors)
        self.toolBar.addAction(self.actionClean)
        self.toolBar.addAction(self.action_ANN)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionAbout)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addSeparator()

        self.retranslateUi(mainWindow)

        self.buttonClearF2.setDefault(False)


        QMetaObject.connectSlotsByName(mainWindow)
    # setupUi

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QCoreApplication.translate("mainWindow", u"IonogramViewer2", None))
        self.actionExit.setText(QCoreApplication.translate("mainWindow", u"Exit", None))
#if QT_CONFIG(tooltip)
        self.actionExit.setToolTip(QCoreApplication.translate("mainWindow", u"Exit (Ctrl+Q)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen.setText(QCoreApplication.translate("mainWindow", u"Open", None))
#if QT_CONFIG(tooltip)
        self.actionOpen.setToolTip(QCoreApplication.translate("mainWindow", u"Open (Ctrl+O)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionHelp.setText(QCoreApplication.translate("mainWindow", u"Help", None))
#if QT_CONFIG(shortcut)
        self.actionHelp.setShortcut(QCoreApplication.translate("mainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("mainWindow", u"About", None))
#if QT_CONFIG(shortcut)
        self.actionAbout.setShortcut(QCoreApplication.translate("mainWindow", u"Alt+F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("mainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("mainWindow", u"Save (Ctrl+S)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionNext.setText(QCoreApplication.translate("mainWindow", u"Next", None))
#if QT_CONFIG(tooltip)
        self.actionNext.setToolTip(QCoreApplication.translate("mainWindow", u"Next (Ctrl + Space)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNext.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+Space", None))
#endif // QT_CONFIG(shortcut)
        self.actionPrevious.setText(QCoreApplication.translate("mainWindow", u"Previous", None))
#if QT_CONFIG(tooltip)
        self.actionPrevious.setToolTip(QCoreApplication.translate("mainWindow", u"Previous (Ctrl + Shift + Space)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionPrevious.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+Shift+Space", None))
#endif // QT_CONFIG(shortcut)
        self.actionReload.setText(QCoreApplication.translate("mainWindow", u"Reload", None))
#if QT_CONFIG(tooltip)
        self.actionReload.setToolTip(QCoreApplication.translate("mainWindow", u"Reload", None))
#endif // QT_CONFIG(tooltip)
        self.actionFirst.setText(QCoreApplication.translate("mainWindow", u"First", None))
        self.actionLast.setText(QCoreApplication.translate("mainWindow", u"Last", None))
        self.actionChangeLayer.setText(QCoreApplication.translate("mainWindow", u"Change layer", None))
#if QT_CONFIG(tooltip)
        self.actionChangeLayer.setToolTip(QCoreApplication.translate("mainWindow", u"Change layer", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionChangeLayer.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+Tab", None))
#endif // QT_CONFIG(shortcut)
        self.actionClose.setText(QCoreApplication.translate("mainWindow", u"Close", None))
#if QT_CONFIG(tooltip)
        self.actionClose.setToolTip(QCoreApplication.translate("mainWindow", u"Close (Ctrl+W)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionClose.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+W", None))
#endif // QT_CONFIG(shortcut)
        self.actionRemote.setText(QCoreApplication.translate("mainWindow", u"Remote", None))
#if QT_CONFIG(tooltip)
        self.actionRemote.setToolTip(QCoreApplication.translate("mainWindow", u"Remote source", None))
#endif // QT_CONFIG(tooltip)
        self.actionClean.setText(QCoreApplication.translate("mainWindow", u"Clean", None))
#if QT_CONFIG(tooltip)
        self.actionClean.setToolTip(QCoreApplication.translate("mainWindow", u"Clean ionogram", None))
#endif // QT_CONFIG(tooltip)
        self.actionMoveLeft.setText(QCoreApplication.translate("mainWindow", u"Move left", None))
#if QT_CONFIG(shortcut)
        self.actionMoveLeft.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionMoveRight.setText(QCoreApplication.translate("mainWindow", u"Move right", None))
#if QT_CONFIG(tooltip)
        self.actionMoveRight.setToolTip(QCoreApplication.translate("mainWindow", u"Move right", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionMoveRight.setShortcut(QCoreApplication.translate("mainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionO_trace.setText(QCoreApplication.translate("mainWindow", u"O-trace", None))
#if QT_CONFIG(tooltip)
        self.actionO_trace.setToolTip(QCoreApplication.translate("mainWindow", u"O-trace", None))
#endif // QT_CONFIG(tooltip)
        self.actionX_trace.setText(QCoreApplication.translate("mainWindow", u"X-trace", None))
#if QT_CONFIG(tooltip)
        self.actionX_trace.setToolTip(QCoreApplication.translate("mainWindow", u"X-trace", None))
#endif // QT_CONFIG(tooltip)
        self.actionIgnore_errors.setText(QCoreApplication.translate("mainWindow", u"Ignore errors", None))
#if QT_CONFIG(tooltip)
        self.actionIgnore_errors.setToolTip(QCoreApplication.translate("mainWindow", u"Ignore errors", None))
#endif // QT_CONFIG(tooltip)
        self.action_ANN.setText(QCoreApplication.translate("mainWindow", u"ANN", None))
        self.menu_File.setTitle(QCoreApplication.translate("mainWindow", u"File", None))
        self.menu.setTitle(QCoreApplication.translate("mainWindow", u"?", None))
        self.menuView.setTitle(QCoreApplication.translate("mainWindow", u"View", None))
        self.dockWidget.setWindowTitle(QCoreApplication.translate("mainWindow", u"Layers", None))
#if QT_CONFIG(tooltip)
        self.doubleSpinBoxF2.setToolTip(QCoreApplication.translate("mainWindow", u"foF2", None))
#endif // QT_CONFIG(tooltip)
        self.radioButtonEs.setText(QCoreApplication.translate("mainWindow", u"Es", None))
        self.buttonClearE.setText("")
        self.buttonClearEs.setText("")
#if QT_CONFIG(tooltip)
        self.doubleSpinBoxF1.setToolTip(QCoreApplication.translate("mainWindow", u"foF1", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.doubleSpinBoxE.setToolTip(QCoreApplication.translate("mainWindow", u"foE", None))
#endif // QT_CONFIG(tooltip)
        self.toolBar.setWindowTitle(QCoreApplication.translate("mainWindow", u"toolBar", None))
#if QT_CONFIG(tooltip)
        self.dockWidget_2.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.dockWidget_2.setWindowTitle(QCoreApplication.translate("mainWindow", u"Parameters", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("mainWindow", u"Parameters of saving", None))
        self.pngDefaultButton.setText(QCoreApplication.translate("mainWindow", u"Set default values", None))
        self.pngCheckBox.setText(QCoreApplication.translate("mainWindow", u"PNG image (up to 10 x 10 inches)", None))
        self.label_7.setText(QCoreApplication.translate("mainWindow", u"dpi", None))
        self.stdCheckBox.setText(QCoreApplication.translate("mainWindow", u"STD file", None))
        self.label_6.setText(QCoreApplication.translate("mainWindow", u"Height (inches)", None))
        self.label_5.setText(QCoreApplication.translate("mainWindow", u"Width (inches)", None))
        self.jsonCheckBox.setText(QCoreApplication.translate("mainWindow", u"JSON file", None))
        self.groupBox.setTitle(QCoreApplication.translate("mainWindow", u"Ionogram parameters", None))
        self.label_4.setText(QCoreApplication.translate("mainWindow", u"Time zone", None))
        self.sunspotNumberLabel.setText(QCoreApplication.translate("mainWindow", u"Sunspot \n"
"number", None))
        self.label_8.setText(QCoreApplication.translate("mainWindow", u"Dip angle (deg.)", None))
        self.longDegLabel.setText(QCoreApplication.translate("mainWindow", u"Long. (deg.)", None))
        self.label.setText(QCoreApplication.translate("mainWindow", u"Station name", None))
        self.label_3.setText(QCoreApplication.translate("mainWindow", u"Date & Time", None))
        self.latDegLabel.setText(QCoreApplication.translate("mainWindow", u"Lat. (deg.)", None))
        self.gyrofrequencyLabel.setText(QCoreApplication.translate("mainWindow", u"Gyro-\n"
"frequency (MHz)", None))
    # retranslateUi

